Added mention of IndiePKG in install instructions.
BetaPictoris/wiki pull request #10
Opened 2022-05-13 16:43 UTC by talwat

Hey there!

A while ago I added your program to [my package manager](https://github.com/talwat/indiepkg)'s repositories.

2022-05-13 18:10 UTC, BetaPictoris requested changes

2022-05-13 18:10 UTC, BetaPictoris commented on docs/readme.md
> +
This is in the "Build from source" section, and should be in a new section, maybe make one called "package managers"?

2022-05-13 19:15 UTC, talwat commented
I've moved it to a different section, let me know if I should make any more changes :)

2022-05-14 01:42 UTC, BetaPictoris commented
The documentation looks pretty good now, but the packag (or IndiePKG itself seems to have a bug), here is the error:
```
=> Error
[!] File /home/beta/.indiepkg/tmp/package_src/wiki/wiki is not a regular file, can't copy.
```

2022-05-14 04:42 UTC, talwat commented
[Fixed](https://github.com/talwat/indiepkg/commit/fae0b51ced947c24e56e38394ed996191572bcb0) it, sorry about that. I assume you changed the install instructions eventually and it threw off indiepkg.

2022-05-14 15:43 UTC, talwat commented
@BetaPictoris should I make any further changes?

2022-05-31 16:29 UTC, BetaPictoris commented
Merging... Thank you, and I apologize for the late reply!

2022-05-31 16:30 UTC, merged